### ISSUE TITLE
Docker image latest tag

### ISSUE THREAD

**Issue by nevmerzhitsky** [EdgedesignCZ/phpqa#100]
Hi!

Please mark the latest image in Docker Registry via `latest` tag too. This is standard for Docker world and many soft uses it by default.

**Comment by zdenekdrahos** [comment]
latest also causes confusion. I don't think that it can be called standard just because it is default tag. 

* https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375
* http://container-solutions.com/docker-latest-confusion/

Is it really necessary? Isn't predictable pipeline (_with specified version_) better? 
Or is there any reason why you can't use `zdenekdrahos/phpqa:v1.16.0`? Some software supports only latest tag?
