### ISSUE TITLE
Option for disabling parallel execution

### ISSUE THREAD

**Issue by vaclav-easymarkit** [EdgedesignCZ/phpqa#13]
It could be helpful especially for the machines with weak CPU performance. I could try to prepare pull-request if you like to.

**Comment by zdenekdrahos** [comment]
I wouldn't specify number of tasks. I see two main use cases:

* run everything in parallel (current behaviour)
* don't use parallelism at all

So I think that simple switch would be good enough. Just like in [--output](https://github.com/EdgedesignCZ/phpqa/pull/4/files#diff-129e06e751fe652f3bf1f2f0af7584d5R45):
```
# run parallel tasks
phpqa
phpqa --execution parallel

# don't use parallelism
phpqa --execution single
phpqa --execution something_else_than_word_parallel
```
If `--execution` equals `parallel` then [ParallelExec](http://robo.li/tasks/Base/#parallelexec) is used. Otherwise tasks are executed sequentially with [Exec](http://robo.li/tasks/Base/#exec).

No BC is introduced (parallel execution is default option) and the solution is extensible in the future (if `--execution` is integer then it can be used as number of parallel processes). It's simple change compared to dividing processes into parallel groups.

**Comment by vaclav-easymarkit** [comment]
Yes, you are right, it will be sufficient.
