### ISSUE TITLE
Hard dependency on tools?

### ISSUE THREAD

**Issue by mindplay-dk** [EdgedesignCZ/phpqa#130]
How come many of the third-party tools (Mess Detector, Code Sniffer, etc.) are listed in the `require` section of `composer.json`?

You don't appear to be using the APIs of these packages - they're all dispatched via the command-line, I think?

If there's no strict dependency on any specific tools, it might not make sense to inherit all of these dependencies - you end up installing tools (and all of the dependencies of those tools) that you may not be using at all.

If some of these are dependencies of the package under test, perhaps they belong in `require-dev`?

**Comment by zdenekdrahos** [comment]
You can ship your package, can't you? Don't depend on `edgedesign/phpqa`, but use your package `company/qa` with locked versions (_[versions are not restricted](https://github.com/EdgedesignCZ/phpqa/pull/102#issuecomment-355354908)_).

* Yes, you might install some tools you aren't using. But is this a big issue? We are talking about dev package, not some production package.

* Yes, you can get dependencies conflicts because of unused tools. But that can happen even with [suggested tools](https://github.com/EdgedesignCZ/phpqa/issues/121).

Right now I don't think that phpqa can and should solve `require-dev` issues. I don't even think that it can be solved (_just like [phar](https://github.com/EdgedesignCZ/phpqa/issues/84#issuecomment-323078240)_).

_Historical context_
phpqa has started with [6 preinstalled tools](https://github.com/EdgedesignCZ/phpqa#available-tools). KISS, so `composer  require edgedesign/phpqa --dev` is better than `composer require edgedesign/phpqa toolA toolB etc`.  [v1.9](https://github.com/EdgedesignCZ/phpqa/blob/master/CHANGELOG.md#v190) has introduced [optional/suggested tools](https://github.com/EdgedesignCZ/phpqa#suggested-tools).

**Comment by mindplay-dk** [comment]
> `composer require edgedesign/phpqa --dev` is better than `composer require edgedesign/phpqa toolA toolB`

I have to disagree.

From the Composer manual section on `"suggests":

> Suggested packages that can enhance or work well with this package. These are informational and are displayed after the package is installed, to give your users a hint that **they** could add more packages, even though they are **not strictly required.**

This describes your exact scenario.

Putting those dependencies in `"requires"` directly encourages people installing your package to "inherit" their own first-order dependencies from your package, without specifying compatible versions, or even specifying their own first-order dependencies at all - inheriting your first-order dependencies from another package is generally bad practice.

It sounds like you're favoring convenience over correctness. There is surely a better way to provide the same level of convenience without misusing Composer - for example a plugin, which might be a good idea either way (whether it's interactive or not) so that first-order dependencies can be correctly added to the project's own `composer.json` post-install.

KISS means keep it *simple* - what you're doing may make things *easier* for users who don't understand Composer, but it actually adds complexity to the dependency management, by trying to side-step a well-defined idiomatic pattern, e.g. using Composer as it was intended, something you *should* expect users of a Composer package to understand, while creating problems for those who do.

Just my two cents.
