### ISSUE TITLE
Provide options from config file

### ISSUE THREAD

**Issue by jonhattan** [EdgedesignCZ/phpqa#175]
I'm not clear why some settings are provided as options (cli arguments) and other ones as config (.phpqa.yml). I guess there're historical reasons.

It would be handy to allow providing options from config file, so all settings are self-contained.

**Comment by zdenekdrahos** [comment]
* [CLI options](https://github.com/EdgedesignCZ/phpqa#analyze) configure used tools, common analyzed and ignored directories
* [.phpqa.yml](https://github.com/EdgedesignCZ/phpqa#advanced-configuration---phpqayml) contains specific configuration for each tool.

I'd like to keep CLI options because:

> I want to analyze selected directory **without** complex configuration and **creating extra files**/tasks
> https://github.com/EdgedesignCZ/phpqa#why

I don't want to add more specific CLI options. That's configured in `.phpqa.yml`. I am not a fan of tool-specific CLI options, like in [rclone](https://rclone.org/flags/).

![Specific CLI options in rclone](https://user-images.githubusercontent.com/7994022/61139087-f148b800-a4c8-11e9-9191-6a24d7c4c77c.png)

**Comment by jonhattan** [comment]
I think I didn't explain it well -  I'd like to pick options from a config file if not provided in cli (I think you understood the opposite).

My primary use case is to set the analyzed/ignored files in .phpqa.yml along with the extensions.

Here's a PR that works for me: https://github.com/EdgedesignCZ/phpqa/pull/176
