### ISSUE TITLE
document the usage of phpcs3

### ISSUE THREAD

**Issue by marcosh** [EdgedesignCZ/phpqa#67]
At the moment the usage of `php_codesniffer` version 3 is not documented.

Moreover, when cloning directly the project, version 2 of `php_codesniffer` is available since the version is locked in `composer.lock`, while when installing the library as a composer dependency, you'll get version 3 since there is no bound on `composer.json`

**Comment by zdenekdrahos** [comment]
What exactly is missing in the documentation?
Both versions are supported. So from my point of view it's up to you, if you are using v2 or v3. Analysis should be same.

Relates issues about "compatibility bugs": [phpcs](https://github.com/EdgedesignCZ/phpqa/issues/49),  [phpmetrics](https://github.com/EdgedesignCZ/phpqa/issues/64), [phpcpd](https://github.com/EdgedesignCZ/phpqa/issues/19#issuecomment-217624511)

**Comment by marcosh** [comment]
Nowhere in the `README` it is mentioned that you should use `phpcs3` instead of `phpcs` to use `v3`.

**Comment by zdenekdrahos** [comment]
You should still use `phpcs`. Take a look at Travis build:

* [phpcs 3.0 is installed](https://travis-ci.org/EdgedesignCZ/phpqa/jobs/234494092#L460)
* `--tools phpcs:0` is executed in [bin/ci.sh](https://github.com/EdgedesignCZ/phpqa/blob/master/bin/ci.sh)

It's not documented because the goal of suporting multiple versions isn't to define version in `--tools`. But use standard identifier `phpcs`. Anyway only version is installed in composer, so it's not even possible to run phpcs2 and phpcs3.

How did you find about `phpcs3`?
