### ISSUE TITLE
phar installation?

### ISSUE THREAD

**Issue by davidmpaz** [EdgedesignCZ/phpqa#84]
Hi,

any reason for not have a phar file built?

thanks in advance

**Comment by zdenekdrahos** [comment]
I've tried and failed. From my experience, it's almost impossible to get working phar for a tool like phpqa. I've already spent almost 4 hours without any usable result. So it's not worth the effort for me...

But I'll merge working phar solution. Feel free to send a PR.
Be aware of following "constraints":

* phar has only one entry point, but phpqa executes multiple processes in `vendor/bin`
* you can't execute tool without process because some tools contains `exit` expression (so phpqa process is exited too)
* path and options issues when internal switch is used (`php phpqa.phar phploc --version`)

In the meantime, I would recommend [docker](https://github.com/EdgedesignCZ/phpqa#docker) as phar alternative.

**Comment by davidmpaz** [comment]
Hi thanks for the highlight. I will stick I think to the clone install locally and docker for CI. Unfortunately I am short of time also these days.

cheers
